from ADM1 import*
plt.figure(1)
plt.plot(tspan, x[:,10],'b', label = 'S_va')
plt.plot(tspan, x[:,11],'r', label = 'S_bu')
plt.plot(tspan, x[:,12],'g', label = 'X_c4')
plt.legend(loc = 'best')
plt.xlabel('time [d]')
plt.ylabel('Concentration')
plt.xlim([0,60])

plt.figure(12)
plt.subplot(3,3,1)
plt.title('Sugar')
plt.plot(tspan, x[:,4], label = 'S_su')
plt.plot(tspan, x[:,5], label = 'X_su')
plt.legend(loc = 'best')
plt.subplot(3,3,2)
plt.title('AmminoA.')
plt.plot(tspan, x[:,6], label = 'S_aa')
plt.plot(tspan, x[:,7], label = 'X_aa')
plt.legend(loc = 'best')
plt.subplot(3,3,3)
plt.title('Fats')
plt.plot(tspan, x[:,8], label = 'S_fa')
plt.plot(tspan, x[:,9], label = 'X_fa')
plt.legend(loc = 'best')
plt.subplot(3,3,4)
plt.title('C4')
plt.plot(tspan, x[:,10], label = 'S_va')
plt.plot(tspan, x[:,11], label = 'S_bu')
plt.plot(tspan, x[:,12], label = 'X_c4')
plt.legend(loc = 'best')
plt.ylabel('[kgCOD/m3]')
plt.subplot(3,3,5)
plt.title('Proprion.')
plt.plot(tspan, x[:,13], label='S_pro')
plt.plot(tspan, x[:,14], label = 'X_pro')
plt.legend(loc = 'best')
plt.subplot(3,3,6)
plt.title('AceticA.')
plt.plot(tspan, x[:,15], label = 'S_ac')
plt.plot(tspan, x[:,16], label = 'X_ac')
plt.legend(loc = 'best')
plt.subplot(3,3,7)
plt.title('Hydrogen')
plt.plot(tspan, x[:,17], label = 'S_h2')
plt.plot(tspan, x[:,18],'b', label = 'X_h2')
plt.legend(loc = 'best')
plt.subplot(3,3,8)
plt.title('CO2-CH4')
plt.plot(tspan, S_co2,label='CO2')
plt.plot(tspan, x[:,19],label='CH4')
plt.legend(loc = 'best')
plt.xlabel('time [d]')
plt.subplot(3,3,9)
plt.title('Biogas')
plt.plot(tspan,Biogas)

#
plt.figure(13); plt.title('Biogas (H2+CH4+CO2)')
plt.plot(tspan[0:2500],Biogas[0:2500])
#


plt.figure(2)
plt.plot(tspan, x[:,27],'r', label = 'S_gas_ch4')
plt.plot(tspan, x[:,28],'b', label = 'S_gas_co2')
plt.legend(loc = 'best')
plt.xlabel('time [d]')
plt.ylabel(' main_gas  concentration [kgCOD/m3]')
plt.xlim([0,60])

plt.figure(3)
plt.plot(tspan, x[:,26],'g', label = 'S_gas_h2')
plt.xlabel('time [d]')
plt.ylabel(' S_gas_h2  concentration [kgCOD/m3]')
plt.xlim([0,1.8])
plt.figure(4)
plt.plot(tspan, x[:,26],'g', label = 'S_gas_h2')
plt.xlabel('time [d]')
plt.ylabel(' S_gas_h2  concentration [kgCOD/m3]')
plt.xlim([0,60])

plt.figure(5)

plt.plot(tspan, P_gas_ch4,'r', label = 'P_gas_ch4')
plt.plot(tspan, P_gas_co2,'b', label = 'P_gas_co2')
plt.legend(loc = 'best')
plt.xlabel('time [d]')
plt.ylabel(' main_gas  partial pressure [bar]')
plt.xlim([0,60])

plt.figure(6)
plt.plot(tspan, P_gas_h2,'g', label = 'P_gas_h2')
plt.xlabel('time [d]')
plt.ylabel('  partial pressure h2 [bar]')
plt.xlim([0,1.8])

plt.figure(7)
plt.plot(tspan, P_gas_h2,'g', label = 'P_gas_h2')
plt.xlabel('time [d]')
plt.ylabel(' partial pressure h2 [bar]')
plt.xlim([0,60])

plt.figure(10)
plt.plot(tspan,x[:,0], label='Inerti')
plt.plot(tspan,x[:,1],label='Carboidrati')
plt.plot(tspan,x[:,2],label='Proteine')
plt.plot(tspan,x[:,3],label='Lipidi')
plt.xlabel('time [d]')
plt.ylabel('kg/m3')
plt.legend(loc='best')
plt.show()

file = open("CH4_content.txt", "w")
for i in range(0,len(tspan)):
    CH4_val = str(x[i, 27])
    time_val = str(tspan[i])
    output = time_val + "\t" + CH4_val
    file.write(output)
    file.write("\n")
file.close

file = open("effluent_biogas_original.txt", "w")
for i in range(0,len(tspan)):
    Bio_val = str(Biogas[i])
    time_val = str(tspan[i])
    output = time_val + "\t" + Bio_val
    file.write(output)
    file.write("\n")
file.close
